# Generated by Django 3.2.2 on 2021-05-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredient',
            new_name='savory',
        ),
    ]
