# Generated by Django 3.2.2 on 2021-05-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_ingredient_product_savory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='soda_level',
            new_name='sugar',
        ),
    ]
